config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

    validates :name, :address, :category, presence: true
    validates :category , inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

    validates :content, :rating, presence: true
    validates :rating, inclusion: { in: (0..5), allow_nil: false }, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
    redirect_to @restaurant
    else
      render :new
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants list</h1>
<%= link_to 'Add a restaurant', new_restaurant_path, class: 'btn btn-primary mb-2' %>
<% @restaurants.each_with_index do |restaurant, index| %>
  <div class="d-grid">
    <p class="p-2 bg-light border"><%= link_to restaurant.name, restaurant_path(restaurant) %></p>
  <div>
<% end %>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, :collection => %w[chinese italian japanese french belgian] %>
  <%= f.submit "Submit", class: 'btn btn-primary' %>
  <%= link_to 'Cancel', restaurants_path, class: "btn btn-secondary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<div class="border p-2 mb-2 bg-secondary text-dark bg-opacity-10">
  <p>Address: <%= @restaurant.address %></p>
  <p>Tel: <%= @restaurant.phone_number %></p>
  <p>Category: <%= @restaurant.category %></p>
</div>

<div class="mb-2">
  <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
  <%= link_to 'Back', restaurants_path, class: "btn btn-secondary" %>
</div>
<h5>Reviews of <%= @restaurant.name %></h5>

<div class="d-grid">
  <% @restaurant.reviews.each do |review| %>
  <div class="border border-secondary p-2 mb-2">
    <p><%= review.content %></p>
    <p>RATING: <%= "⭐ " * review.rating %></p>
  </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h5>Add a review</h5>

<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, input_html: { min: 0, max: 5 } %>
  <%= f.submit "Submit", class: 'btn btn-primary' %>
  <%= link_to 'Cancel', restaurants_path, class: "btn btn-secondary" %>
<% end %>